# -*- coding: utf-8 -*-

{
    'name': "Ike Event (Purchase)",
    'summary': """Custom NU""",
    'author': "AlsibaMx",
    'license': 'LGPL-3',
    'category': 'Uncategorized',
    'version': '18.0.1.0.0',
    'depends': [
        'purchase',
        'project_purchase',
        'custom_master_catalog',
        'ike_event',
        'sh_all_in_one_helpdesk',
        'ike_event_portal',
        'custom_o2m_track',
        'base_tier_validation',
    ],
    "data": [
        'security/ir_module_security.xml',
        'security/ir.model.access.csv',
        'data/authorized_amount_request_data.xml',
        'data/authorized_amount_request_tier_data.xml',
        "data/purchase_email_data.xml",
        "data/ike_event_purchase_data.xml",
        "data/mail_template_data.xml",
        'data/ir_config_parameter_data.xml',
        "wizard/sh_helpdesk_ticket_assignment_wizard.xml",
        "wizard/ike_event_confirm_costs_wizard.xml",
        "views/ike_event_screen_views.xml",
        "views/tier_validation_button_views.xml",
        "views/ir_sequence_views.xml",
        "views/project_project_views.xml",
        "views/authorized_amount_request_views.xml",
        "views/purchase_order_views.xml",
        "views/res_partner_supplier_views.xml",
        "views/res_config_settings_views.xml",
        "views/purchase_order_portal_report.xml",
        "views/portal_purchase_templates.xml",
        "views/sh_helpdesk_ticket_views.xml",
        "views/ike_menus.xml",
    ],
    "assets": {
        'web.assets_frontend': [
            'ike_event_purchase/static/src/js/purchase_portal_sidebar.js',
            'ike_event_purchase/static/src/js/components/purchase_order_details/*.*',
            'ike_event_purchase/static/src/js/components/purchase_order_dispute/*.*',
            'ike_event_purchase/static/src/js/components/purchase_orders_list/*.*',
            'ike_event_purchase/static/src/js/components/purchase_rfq_list/*.*',
        ],
        'web.assets_backend': [
            'ike_event_purchase/static/src/xml/systray_notification_view.xml',
            'ike_event_purchase/static/src/xml/ticket_dashboard_card_view.xml',
            'ike_event_purchase/static/src/xml/tier_review_amounts.xml',
            'ike_event_purchase/static/src/js/chatter_notebook_widget.js',
            'ike_event_purchase/static/src/css/*.*',
            'ike_event_purchase/static/src/js/tier_review_amounts.js',
            'ike_event_purchase/static/src/css/chatter_fix.css',
        ]
    }
}
