# -*- coding: utf-8 -*-

{
    'name': "Ike Master Catalog",
    'summary': """Master Catalog for IKE""",
    'author': "AlsibaMx",
    'license': 'LGPL-3',
    'category': 'Uncategorized',
    'version': '18.0.1.0.3',
    'depends': [
        'base',
        'web',
        'portal',
        'custom_disable_records',
        'custom_o2m_track',
        'contacts',
        'stock',
        'purchase',
        'hr',
        'sale',
        'fleet',
        'survey',
    ],
    "data": [
        "security/ir_module_security.xml",
        "security/ir.model.access.csv",
        "data/res_partner_account_data.xml",
        "data/data.xml",
        "data/ir_sequence_data.xml",
        "views/product_product_views.xml",
        "views/product_category_service_views.xml",
        "views/product_template_subservice_views.xml",
        "views/product_template_views.xml",
        "views/res_partner_views.xml",
        "views/res_partner_client_views.xml",
        "views/res_partner_account_views.xml",
        "views/res_partner_supplier_views.xml",
        "views/res_partner_supplier_center_views.xml",
        "views/res_partner_company_ike_views.xml",
        "views/res_users_views.xml",
        "views/fleet_vehicle_model_brand_views.xml",
        "views/fleet_vehicle_model_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/fleet_vehicle_model_category_views.xml",
        "views/other/hr_employee_views.xml",
        "views/other/res_company_views.xml",
        "views/other/res_currency_views.xml",
        "views/other/res_country_views.xml",
        "views/other/res_country_state_views.xml",
        "views/other/custom_hide_admin_views.xml",
        "views/product_template_concepts_views.xml",
        "views/product_template_accesory_views.xml",
        "views/other/custom_phone_classification_views.xml",
        "views/other/custom_uom_uom_views.xml",
        "views/other/custom_product_mapping_views.xml",
        "views/other/custom_account_identification_views.xml",
        "views/other/custom_account_type_views.xml",
        "views/other/custom_state_municipality_views.xml",
        "views/other/custom_holidays_views.xml",
        "views/other/custom_supplier_type_views.xml",
        "views/other/custom_payment_type_views.xml",
        "views/other/custom_type_event_views.xml",
        "views/other/custom_supplier_coverage_configuration_views.xml",
        "views/other/custom_geographical_area_views.xml",
        "views/other/custom_vehicle_type_views.xml",
        "views/other/custom_vehicle_wieght_category_views.xml",
        "views/other/custom_supplier_types_statuses_views.xml",
        "views/other/custom_reason_authorizing_additional_costs_views.xml",
        "views/other/custom_additional_concept_authorizer_type_views.xml",
        "views/other/res_partner_supplier_drivers_rel_views.xml",
        "views/other/res_partner_supplier_users_rel_views.xml",
        "views/other/custom_data_source/custom_data_source_views.xml",
        "views/other/custom_subservice_specification_views.xml",
        "wizard/custom_import_postal_codes_views.xml",
        "wizard/custom_geographic_subservice_wizard.xml",
        "wizard/custom_model_confirm_wizard.xml",
        "views/res_partner_menus.xml",
        "views/other/res_config_settings_views.xml",
        'security/cleanup_menus.xml',  # TODO Delete in sprint18 or after the client has updated their database with this code
    ],
    'assets': {
        'web.assets_backend': [
            'custom_master_catalog/static/src/css/tags_list.css',
            'custom_master_catalog/static/src/scss/fields.scss',
            'custom_master_catalog/static/src/views/*.*',
            'custom_master_catalog/static/src/fields/*.*',
            'custom_master_catalog/static/src/widgets/*.*',
        ],
    },
}
