# -*- coding: utf-8 -*-
{
    'name': 'IKE Events',
    'summary': '''''',
    'author': 'Alsiba MX',
    'website': 'https://www.linkedin.com/in/neftalimich',
    'license': 'LGPL-3',
    'category': 'Uncategorized',
    'version': '18.0.1.0.3',
    'depends': [
        'base', 'web', 'mail', 'bus', 'base_geolocalize',
        'account', 'survey', 'fleet',
        'custom_nu', 'custom_supplier_cost_matrix',
    ],
    'data': [
        'security/ir_module_security.xml',
        'data/survey_data.xml',
        'data/survey_satisfaction_data.xml',
        'data/ike_event_data.xml',
        'data/ike_event_flow_data.xml',
        'data/ir_sequence_data.xml',
        'data/ike_event_service_type_data.xml',
        'security/ir.model.access.csv',
        'wizard/ike_event_add_manual_wizard.xml',
        'wizard/ike_event_confirm_wizard.xml',
        'wizard/ike_event_vehicle_wizard.xml',
        'wizard/ike_event_duplicate_wizard.xml',
        'wizard/ike_event_change_state_supplier_wizard.xml',
        'wizard/ike_event_assignment_wizard.xml',
        'wizard/ike_event_phone_view_wizard.xml',
        'views/ike_event_supplier_views.xml',
        'views/ike_event_stage_views.xml',
        'views/service_models/ike_service_stage_views.xml',
        'views/survey/survey_survey_views.xml',
        'views/survey/survey_input_views.xml',
        'views/survey/survey_question_views.xml',
        'views/survey/survey_templates.xml',
        'views/service_models/ike_service_input_medical_views.xml',
        'views/service_models/ike_service_input_vial_views.xml',
        'views/service_models/ike_service_input_vial_truck_views.xml',
        'views/service_models/ike_service_input_vial_generic_views.xml',
        'views/product_models/product_category_service_views.xml',
        'views/event_flow_models/ike_event_cancellation_reasons.xml',
        'views/event_flow_models/ike_supplier_assignment_type_views.xml',
        'views/product_models/product_template_subservice_views.xml',
        'views/ike_event_views.xml',
        'views/ike_event_duplicate_reason.xml',
        'views/ike_event_evidence_views.xml',
        'views/ike_event_service_count.xml',
        'views/ike_event_service_summary.xml',
        'views/ike_event_screen_views.xml',
        'views/ike_event_authorization_views.xml',
        'views/ike_event_history_view.xml',
        'views/ike_event_flow_views.xml',
        'views/ike_event_service_type.xml',
        'views/ike_event_fleet_views.xml',
        'views/ike_menus.xml',
        'security/cleanup_menus.xml',  # TODO Delete in sprint22 or after the client has updated their database with this code
        'templates/ike_event_supplier_portal_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ike_event/static/src/scss/ike_fields.scss',
            'ike_event/static/src/scss/ike_widget_field.scss',
            'ike_event/static/src/css/*.css',
            'ike_event/static/src/services/*.js',
            'ike_event/static/src/systray/**/*.*',
            'ike_event/static/src/views/*.*',
            'ike_event/static/src/views/list/*.*',
            'ike_event/static/src/widgets/**/*.*',
            'ike_event/static/src/fields/**/*.*',
            'ike_event/static/src/custom_fleet_dashboard_loader.js',
            # 'ike_event/static/src/ike_dashboard_event_loader.js',
        ],
        'web._assets_primary_variables': [
            'ike_event/static/src/scss/bootstrap_extension.scss',
        ],
        'ike_event.custom_fleet_dashboard_bundle': [
            ('include', 'web._assets_helpers'),
            ('include', 'web._assets_backend_helpers'),
            'ike_event/static/src/dashboard/**/*.*',
        ],
        # 'ike_event.ike_dashboard_event_bundle': [
        #     ('include', 'web._assets_helpers'),
        #     ('include', 'web._assets_backend_helpers'),
        #     'ike_event/static/src/dashboard/**/*.*',
        # ],
        'web.assets_frontend': [
            'ike_event/static/src/portal/*.*',
        ],
    },
    'application': True,
}
